// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aevaxrhfwjvttutxbeul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldmF4cmhmd2p2dHR1dHhiZXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTAwMzEsImV4cCI6MjA2MjU4NjAzMX0.X97feKEppKLzcHWtR9600legFNG0-AqFWFeK3Tu1HO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);